name: "Deploy"
on:
  push:
  workflow_dispatch:

jobs:
  export-web:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_SECRET_ACCESS_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: peak-github-actions-demo
          source_dir: 'web'
          destination_dir: ''